### ISSUE TITLE
3.0.2 beta-12 failed bridge due to exception; Google Chrome/Chromium not found

### ISSUE THREAD

**Issue by rodesch-ryan** [bwmp/MultiShock#5]
## 3.0.2 Beta 12 issue

File location: D:\Tools\
OS version: Windows 11 Home Build 10.0.22631 Build 22631
Chrome is _not installed_ on my machine

Executable fails on launch due to tracebacks below

```
'FrontendStream' object has no attribute 'fileno'

Traceback (most recent call last):
  File "bridge.py", line 299, in <module>
  File "eel\__init__.py", line 174, in start
  File "eel\__init__.py", line 206, in show
  File "eel\browsers.py", line 77, in open
OSError: Can't find Google Chrome/Chromium installation

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bridge.py", line 308, in <module>
  File "eel\__init__.py", line 174, in start
  File "eel\__init__.py", line 206, in show
  File "eel\browsers.py", line 75, in open
  File "eel\edge.py", line 13, in run
  File "subprocess.py", line 837, in __init__
  File "subprocess.py", line 1304, in _get_handles
AttributeError: 'FrontendStream' object has no attribute 'fileno'
```
Recommend using Edge or OS default browser path as oppose to Google Chrome.

**Comment by bwmp** [comment]
google chrome was the default for eel. next update will attempt brave, then chrome, then if both of those could not be found it will open the page in your default browser. the default was chrome due it it supporting app mode allowing the program to look like a standalone app
